#include "i2c_bus.h"
#include "mcu_pinmap.h"

// I2C_HandleTypeDef hi2c1; // Defined in main.c or generated by CubeMX

/**
 * @brief Initializes the I2C bus.
 *        This function configures I2C1 peripheral.
 * @retval HAL_StatusTypeDef HAL_OK if initialization is successful, HAL_ERROR otherwise.
 */
HAL_StatusTypeDef i2c_bus_init(void)
{
    hi2c1.Instance = I2C1;
    hi2c1.Init.ClockSpeed = I2C_BUS_SPEED_FAST_MODE;
    hi2c1.Init.DutyCycle = I2C_DUTYCYCLE_2;
    hi2c1.Init.OwnAddress1 = 0;
    hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.OwnAddress2 = 0;
    hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;

    if (HAL_I2C_Init(&hi2c1) != HAL_OK)
    {
        // Fallback to standard mode if fast mode fails
        hi2c1.Init.ClockSpeed = I2C_BUS_SPEED_STANDARD_MODE;
        if (HAL_I2C_Init(&hi2c1) != HAL_OK)
        {
            return HAL_ERROR;
        }
    }
    return HAL_OK;
}

/**
 * @brief Reads a sequence of bytes from a device's internal register.
 */
HAL_StatusTypeDef i2c_mem_read(uint16_t dev_address, uint16_t reg_address, uint8_t *pData, uint16_t Size)
{
    return HAL_I2C_Mem_Read(&hi2c1, dev_address, reg_address, I2C_MEMADD_SIZE_8BIT, pData, Size, HAL_MAX_DELAY);
}

/**
 * @brief Writes a sequence of bytes to a device's internal register.
 */
HAL_StatusTypeDef i2c_mem_write(uint16_t dev_address, uint16_t reg_address, uint8_t *pData, uint16_t Size)
{
    return HAL_I2C_Mem_Write(&hi2c1, dev_address, reg_address, I2C_MEMADD_SIZE_8BIT, pData, Size, HAL_MAX_DELAY);
}

