#include "log_uart.h"
#include "mcu_pinmap.h"
#include <stdarg.h>
#include <stdio.h>
#include <string.h>

#ifdef ENABLE_LOG_UART

// UART_HandleTypeDef huart2; // Defined in main.c or generated by CubeMX

/**
 * @brief Initializes the UART for logging.
 */
HAL_StatusTypeDef log_uart_init(void)
{
    huart2.Instance = USART2;
    huart2.Init.BaudRate = 115200;
    huart2.Init.WordLength = UART_WORDLENGTH_8B;
    huart2.Init.StopBits = UART_STOPBITS_1;
    huart2.Init.Parity = UART_PARITY_NONE;
    huart2.Init.Mode = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;

    return HAL_UART_Init(&huart2);
}

/**
 * @brief Sends a formatted string over UART.
 */
int log_uart_printf(const char* format, ...)
{
    char buffer[256];
    va_list args;
    va_start(args, format);
    
    int len = vsnprintf(buffer, sizeof(buffer), format, args);
    va_end(args);
    
    if (len > 0 && len < sizeof(buffer))
    {
        HAL_UART_Transmit(&huart2, (uint8_t*)buffer, len, HAL_MAX_DELAY);
    }
    
    return len;
}

/**
 * @brief Sends a string over UART.
 */
HAL_StatusTypeDef log_uart_send_string(const char* str)
{
    uint16_t len = strlen(str);
    return HAL_UART_Transmit(&huart2, (uint8_t*)str, len, HAL_MAX_DELAY);
}

#endif // ENABLE_LOG_UART

