M48
; DRILL file {KiCad 9.0.2} date 2025-08-19T18:26:07-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-19T18:26:07-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X32.6Y-45.826
X32.6Y-51.606
T2
X27.5Y-27.5
X27.5Y-57.5
X87.5Y-27.5
X87.5Y-57.5
M30
